apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-non-prod

resources:
- namespace.yaml
- ../../base/gateway

patches:
- patch: |-
    - op: add
      path: '/spec/listeners/0/allowedRoutes/namespaces/selector/matchLabels/gateway-environment'
      value: non-production
  target:
    kind: Gateway
- patch: |-
    - op: add
      path: '/metadata/labels'
      value: 
        environment: non-production
  target:
    kind: Namespace