apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-prod

resources:
- namespace.yaml
- ../../base/gateway

patches:
- path: allowed-routes-patch.yaml
  target:
    kind: Gateway
- path: namespace-patch.yaml
  target:
    kind: Namespace
