- op: add
  path: '/spec/parentRefs/0/namespace'
  value: gateway-non-prod
- op: replace
  path: '/spec/hostnames'
  value:
    - "dev.example.com"
    - "example.com"
- op: add
  path: '/spec/rules/0/matches/1'
  value:
    headers:
      - name: environment
        value: dev
        type: Exact