apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- namespace.yaml
- ../../base/backend

patches:
  - patch: |-
      - op: add
        path: '/metadata/labels/gateway-environment'
        value: non-production
    target:
      kind: Namespace
  - patch: |-
      - op: add
        path: '/spec/parentRefs/0/namespace'
        value: gateway-non-prod
      - op: add
        path: '/spec/hostnames'
        value:
          - "dev.example.com"
    target:
      kind: HTTPRoute