apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- namespace.yaml
- ../../base/backend

patches:
  - path: common-labels-patch.yaml
    target:
      name: backend
  - path: namespace-patch.yaml
    target:
      kind: Namespace
  - path: http-route-patch.yaml
    target:
      kind: HTTPRoute
